apiVersion: v1
kind: Secret
metadata:
    name: ingester-env
    namespace: iot
type: Opaque
stringData:
    MQTT_PASSWORD: ENC[AES256_GCM,data:+wThvkJlCl7CvU3ClR+l7bNEx/7CZwKIAV90h6Sw3zY=,iv:x0H8nqIN/wiy6fQBSRAh+MfpMpo7Nh/ZDvMW/1NPKOE=,tag:NeiTGtPEBjkNZ2xXz/rgUQ==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:j3p3BrToSiZ9NM/k5n9dau3bHEoPqFX64KhDhHc89Mo=,iv:QbLVTw5/PbBZXXS9NhaT+IOWZryFkK9T94I0FNqWN18=,tag:00lg8DX46ILnIc7iHqjNwA==,type:str]
sops:
    age:
        - recipient: age10cfekujzrx75r4lce6mnyaxfu2xm7jej98egtt3f9fewj4gl756qda2hm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaHZpdEttaGJhdEJFZ3VP
            VWg4YjJRenNaQ1gwaE9sY1MzSFNhRHhWKzNVCmFpcVBNL2IzbkxGQWVkL3ppdDF6
            VUpQbm1tVDl0dlpxL3h3MytIWFdmaHcKLS0tIGJCQjBzZThiWkhwUFkzK2VvdHFv
            a3Zmb2tKQ1E3UVEybXh5TWdicWszTVkKbB+9i2LjqeYUxE0PvmUMG9UJmmtN/6q9
            CInjKHC7gH4iYOT8JUepTXiaIDv5ex8Qs8p1bx2x3IdlWoP+sQF/tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T15:08:09Z"
    mac: ENC[AES256_GCM,data:JHgIkZaSkQJ8cfBaeAJUaqyUhIIhR8SxlohxI3ZcyUSYdNFoloxzubBTtAxprsrbTsfGOKefk3RDu71RSN/9ie1pCbZUTTRmufH+lGWonykVyB1upPCrYTZN8sN7L/YXR4hoIVAivZpMiEhBwHqVt2pJUymC8fzBEDS6ZeYKmDc=,iv:YEbwgEFaV/XwdAFQbHoIlE6Etnoobqv2rw8qfdYVOAQ=,tag:llwdQxrZCKsMaANx1Pn9Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
