apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingester
  labels:
    app: ingester
spec:
  selector:
    matchLabels:
      app: ingester
  endpoints:
    - port: metrics
      interval: 30s
