apiVersion: v1
kind: Secret
metadata:
    name: mock-publisher-env
    namespace: iot
type: Opaque
stringData:
    MQTT_PASSWORD: ENC[AES256_GCM,data:1gqH/QVF9RF8Wo+d1CZbdrf+OiI7OquA4zSHhCywspA=,iv:TU3ZOYUg1y+69K/4rNVMlL8ilHcpcmAEehmc6zvdvoE=,tag:DbGr32bdwoVGLMsHFeaNUA==,type:str]
sops:
    age:
        - recipient: age10cfekujzrx75r4lce6mnyaxfu2xm7jej98egtt3f9fewj4gl756qda2hm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TWZSZFA1L29KbW0rTThL
            R3hZTXBaUFFmdC9sTHgwQlJnSjRIbitoWFdNClJIUTZ0RFZFcDhpcm9YY2U0YXcx
            ZWMyZlVOQUFhUmthYmhpRHNLenVRQzQKLS0tIEt5OWdoSGs4UXBnYzBoVDRIZjIv
            dGZjYkxJUUJnTXkrSDV0d0MrUEdHNW8KwEWRiXCGC7f8RWm5kXtOMmDtWAn2Dj6l
            eQmOw8LvvP3Bk8pFiJbFkxGi1T+ObXsKoqB3rGEpng9UYvFPOKu5ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T15:29:11Z"
    mac: ENC[AES256_GCM,data:jw1bGZzUNQZ8kzNFnLYlLMcpsXxZvdDS+Iu5fkffEYfR3elQwP+vf9R7l5tJ2j7iA3ut5Z0MCy+6lLtA7ZdyY7KlsjxtyzOjylYPxe9fwzStro+Tup9BQuKFOMUuQcnwcX6jUM1AX4oxCYjK5KXWyyWdgVUGzmYBoc7ly+ucwPM=,iv:O0BtCRt2EFw+wRCjl+aX6Q30uEmJqJaqFk5HfCgfSyw=,tag:V+weNezxzYaNxtKgXUUF4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
