apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-credentials
    namespace: iot
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:ssyVWsQfyrH7dhLh1qJih4fh88+Pk/v/wHSuyRj2PVg=,iv:ure29JbIvJEY38l9ryoSOOCtCRkqsFZoar2JZE3CkAc=,tag:WLd2efHyRZDTQYUPTUIJ9w==,type:str]
    ingester-password: ENC[AES256_GCM,data:UjIDYJ2i30qbM3a6XyXeELhft1xF8e78j7VHED4xnAo=,iv:p/ytNJVJvDMPqrzDdfQooyvZ9pNuYeln90hwG4QfZx4=,tag:dO4GSHLNtjsRsg7UJ6wlrQ==,type:str]
    dashboard-password: ENC[AES256_GCM,data:PXO0M+2ydqt1xBEomL3psFOX4vtV0ypAnDienoixdhw=,iv:YX4KLfRWQ4o41iTnrdrpYAXSgH9i3Vr03GjlmZcqayY=,tag:UnKetutcI/9APBggKTZx7g==,type:str]
sops:
    age:
        - recipient: age10cfekujzrx75r4lce6mnyaxfu2xm7jej98egtt3f9fewj4gl756qda2hm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WWVFK2tPR2NibE11cmt5
            Tzh1QzVkN0phVmpDaWZaWUpZZEwxWkYvS1JNClVwcEhkKzNjTFJVVzFrYnZQV2gx
            Q3ZzWmkwNUtyNEppVU84NE44ZGdnMVkKLS0tIHFpL3JhSlZ0YmZvSWo1OFhOOEZo
            ek5kaThtbC93bmVGMU02NFV1YnVqN1kKUpokAJALemEuD/oagSwgEJhFStjUHHua
            q1LvRw2Xnu+axS5QHcezAYLlzU4bzU9+oEmPb/3iX/cYJ3rqVFgktA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T15:08:09Z"
    mac: ENC[AES256_GCM,data:HFooWOk352LXMRW4vMH8JEwEFrRI79RFuC2FKoqLdo1/No8PCQEzgzuxAiyb/yJ7VN1gdoFThHrzj9XzQVopi5uWqJXvZucYnSak2xTZ91B85oub7l7ahEHAbcCsDSs2755e2XG/OpDODa5ZqapmcbZIj+BUJK/CX2JYPiClNcI=,iv:CyFPLb5bmKmRX4ZU5wA+CORhaXZHrl/SsZgtcwwxAl8=,tag:8FK5AkrE1QGIngqQRlum5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
