# MQTT -> ClickHouse ingester
[package]
name = "ingester"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
rumqttc.workspace = true
clickhouse.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum.workspace = true
anyhow.workspace = true
