apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
  - secret-config.enc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
