apiVersion: v1
kind: Secret
metadata:
    name: rumqttd-config
    namespace: iot
type: Opaque
stringData:
    rumqttd.toml: ENC[AES256_GCM,data:LmV4rYxuhPT31MpjUwFc4PXXEut86b4JcXCkFTkSgZiEgdpbvy7YVndbndnTHI6Ehi6oH23TF/UqYc7Dy9VzaWQldbbTd84AlejFvwVGbjZy5N7ESt9FJDFbEAN+0i02vItwNyTrzzSJsNaV3LVEyzoA0IMretMuEVUPJ7TX3Wx4aYaeewxBAhPPprqKo2GCR0TwRvmWIwQaCuvX76knoICvCNEH0MHtdDVJ4rcJbwWm6B0bmUiylOawY0JD2pNpOj6FNZbxIcYPTxZhxGRrujOmv9zeyH+d9xNW7NBV/3yzG9e8UL9WkWei2VpNeJV5YEIWTK5eXxrysCsC69hZXMnlzrkMSaXyrZhLxh3naevSE+JiToyfqashh7O7HUDbsB791IVyiyI8b55eIoYf0lFyDbbePr1P1mqWQd61y371EvIfjmxhxus7llrLK1awobpOeuR+JRkfx28TuHbz4rM0balMZrVgGQLq6kJ36plCQ8AGEpAqOcZH8kzNjosG0MRny8IQ4LyqLD8QYjDMJCgzRB6mt/XfSbcT5LbF3/DLT1l6Rtba0GPmFuxacBNMWMmCIP+6R6BzV/c8Ln2ZjxRlnNzuwHr36vVrfn2MupUy/FQ9/kxS3YzVpRxqh3aKt5J6U+vA/Q7AOdK8oZEiaKJ+kYLkHQwEiMvxGvx6v5yTMRsPSaRm0EXknf3U21mGURzyjqaw+tc6pM9On+/RKoJHLH3APAMwTQAgYLUF/6Ke9kc2nAfPVrFMuV3a,iv:nLMmX8xXD7xg7iPA/NkFcpvtcezp4X9lxbIIEjVUQxc=,tag:KgQq8xF3gEM9Ze8QfZL9cg==,type:str]
sops:
    age:
        - recipient: age10cfekujzrx75r4lce6mnyaxfu2xm7jej98egtt3f9fewj4gl756qda2hm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMHdSUmNaK0FoSHZEOTI4
            Nyt5ckhsVElCODNmbVN3NmFyZDNUUXNrdTBVCitXVVRaVkJtZW1SL0dXb3JEbnVF
            Qm1idTk1d2FoYnVscTZib2RNU09HdG8KLS0tIHZMVzJZMzZTci92MUNINVRFdHdi
            MEk5b3J2ODBJYWora3YydEtES05VdEEKbLvaXGBE5uieVE9wQ2Ol4ROwX9rAsUFr
            O53PRKALGib9ZOIx5ZJQnhpHvqybdL9HIKcwvFXQOtbJgifnyp/Amg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T15:08:09Z"
    mac: ENC[AES256_GCM,data:fXi7QizM+k3JLSN8KhT5S6+aJEJk7tXZmMsZs7cabwRQmwejbFd2gJ34OTqqvJom8pfFjw70l7j1vk/Z2O71yCFuiBIlW/dtS41sqB/d9ewxeAFLalsruh69D+qbrD5kTqOgarxmo2YzxAciKLek9SCn9/KoR3xyUU/j4IHMb8s=,iv:bxNdmU0ukeSC0C+GbiP8rNZqAoMZHDdE7jxc4MHZ02M=,tag:xqD1cymCycKHlnkfvbq1Ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
