apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rumqttd
  labels:
    app: rumqttd
spec:
  selector:
    matchLabels:
      app: rumqttd
  endpoints:
    - port: metrics
      interval: 30s
